// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class Candidate_Detail
{
    public int Candidate_Id { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public string Qualification { get; set; }

    public string File_Name { get; set; }

    public string File_Content_Type { get; set; }

    public byte[] Candidate_FileData { get; set; }
}