// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class File_Upload
{
    public int File_Id { get; set; }

    public string File_Name { get; set; }

    public byte[] Byte_File { get; set; }

    public string Content_Type { get; set; }
}